# Site settings
title: Salesforce Blog
brand: Robin Smith Software
email: robin@mrrobinsmith.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mrrobinsmith.com" # the base hostname & protocol for your site
github_username:  robinrob

# Build settings
markdown: kramdown
author: Robin Smith

# Allow /index route in place of /index.html etc
permalink: pretty